CREATE TABLE IF NOT EXISTS FILE_SAVERS(ID INT NOT NULL AUTO_INCREMENT
, FILE_SAVER_NAME VARCHAR(60) NOT NULL
, CREDENTIAL_TOKEN VARCHAR(255) NOT NULL
, VERSION INT NOT NULL DEFAULT 0 
, UNIQUE UQ_FILE_SAVER_1 (CREDENTIAL_TOKEN)
, PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS FILE_INFORMATION (
ID INT NOT NULL AUTO_INCREMENT
, FILE_PATH VARCHAR(255) NOT NULL
, FILE_SAVER_ID INT NOT NULL
, REMOTE_ID VARCHAR(255)
, MD5 VARCHAR(64) NOT NULL
, LAST_MODIFIED BIGINT
, VERSION INT NOT NULL DEFAULT 0
, UNIQUE UQ_FILE_1 (FILE_PATH, FILE_SAVER_ID, REMOTE_ID)
, PRIMARY KEY (ID)
, CONSTRAINT FK_FILE_INFORMATION_SAVERS_1 FOREIGN KEY (FILE_SAVER_ID)
REFERENCES FILE_SAVERS(ID)
);


CREATE TABLE IF NOT EXISTS POLICY (ID INT NOT NULL AUTO_INCREMENT
,POLICY_NAME VARCHAR(255) NOT NULL
,AREA_THRESHOLD INT NOT NULL
,INERTIA BIGINT NOT NULL
,MOTION_DETECTION BOOLEAN NOT NULL
,MOTION_DETECT_INTERVAL BIGINT
,MOTION_INERTIA BIGINT
,OUTFOLDER VARCHAR(255)
,GOOGLE_REFRESH_TOKEN VARCHAR(255)
,DROPBOX_REFRESH_TOKEN VARCHAR(255)
,STREAM_PORT INT
,APPLIED BOOLEAN NOT NULL
,DATE_SENT DATE NOT NULL
,DATE_APPLIED DATE NOT NULL
,PRIMARY KEY(ID)
);